version: "3.9"

services:
  database:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    container_name: sport_bot_v2_db
    ports:
      - "5432:5432"
    env_file: .env

volumes:
  postgres_data:
