"""project_settings

Revision ID: 210c21d4086d
Revises: 4ce66ee364e1
Create Date: 2024-01-14 12:07:38.049340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '210c21d4086d'
down_revision: Union[str, None] = '4ce66ee364e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('menu_image_path', sa.String(), nullable=False),
    sa.Column('menu_image_telegram_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_settings')
    # ### end Alembic commands ###
