"""category-lentgh

Revision ID: 400f3cad1bb2
Revises: 3eed026c8440
Create Date: 2024-01-27 17:11:15.635240

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "400f3cad1bb2"
down_revision: Union[str, None] = "3eed026c8440"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "category",
        "title",
        existing_type=sa.VARCHAR(length=30),
        type_=sa.String(length=255),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "category",
        "title",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=30),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
