name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install SSH key
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/aws-key.pem
        chmod 600 ~/.ssh/aws-key.pem
        ssh-keyscan -t rsa ${{vars.AWS}} >> ~/.ssh/known_hosts

    - name: Deploy to remote server
      run: |
        ssh -i ~/.ssh/aws-key.pem ubuntu@${{ vars.AWS }} 'cd /opt/sport_bot_v2/ &&
        export SERVER_NAME=${{ vars.AWS }} &&
        source /opt/sport_bot_v2/venv/bin/activate &&
        git fetch &&
        git checkout ${{ vars.CI_COMMIT_BRANCH }} &&
        git pull origin ${{ vars.CI_COMMIT_BRANCH }} &&
        pip install -r requirements.txt &&
        sudo supervisorctl stop all &&
        python scripts/backup.py &&
        alembic upgrade head &&
        sudo cp etc/nginx/sites-available/* /etc/nginx/sites-available/. &&
        sudo ln -sf /etc/nginx/sites-available/backend.conf /etc/nginx/sites-enabled/ &&
        sudo cp etc/supervisor/conf.d/* /etc/supervisor/conf.d/. &&
        sudo supervisorctl reread &&
        sudo supervisorctl update &&
        sudo supervisorctl start all &&
        sudo service nginx restart'
