name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install SSH key
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/aws-key.pem
        chmod 600 ~/.ssh/aws-key.pem
        ssh-keyscan -t rsa ${{vars.AWS}} >> ~/.ssh/known_hosts

    - name: Deploy to remote server
      run: |
        ssh -i ~/.ssh/aws-key.pem ubuntu@${{ vars.AWS }} 'cd /opt/sport_bot_v2/ &&
        export SERVER_NAME=${{ vars.AWS }} &&
        source /opt/sport_bot_v2/venv/bin/activate &&
        git fetch &&
        git checkout main &&
        git pull origin main &&
        pip install -r requirements.txt &&
        supervisorctl stop all &&
        alembic upgrade head &&
        cp config/etc/nginx/sites-available/* /etc/nginx/sites-available/. &&
        ln -sf /etc/nginx/sites-available/backend.conf /etc/nginx/sites-enabled/ &&
        cp config/etc/supervisor/conf.d/* /etc/supervisor/conf.d/. &&
        supervisorctl reread &&
        supervisorctl update &&
        supervisorctl start all &&
        service nginx restart'
